version: 2

jobs:
  build:
    working_directory: /go/src/telemetry
    docker:
      - image: golang:1.13.4
        environment:
          - INFLUX_URL: http://127.0.0.1:8086
          - GO111MODULE: "on"
          - RUN_ONCE: true
      - image: influxdb:1.7.7-alpine
    steps:
      - checkout
      - run:
          name: Create Directory
          command: |
            mkdir -p .coverage
      - run:
          name: Build
          command: |
            go build -o telemetry
      - run:
          name: Go Test
          command: |
            go test -vet=off -v -tags test -coverprofile=/tmp/cov.out ./...
      - run:
          name: Go Tool
          command: |
            go tool cover -html=/tmp/cov.out -o=.coverage/cov.html
      - store_artifacts:
          path: .coverage
          destination: coverage
